spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: notification-service
      
server:
  port: 3032
